### PR TITLE
Add call!, queue and commit commands

### PR DESCRIPTION
**Pull request by bsedin**
Hello, Michael!

What do you think about adding `call!`, `queue` and `commit` commands to nest?

### CODE REVIEW

**Comment by soveran** [comment]
Hey @kressh, I think it's a good idea :-)

We can add some test cases too and document the feature, but if you prefer we can merge this directly and later we add the rest. What do you think?

**Comment by kressh** [comment]
@soveran, sorry for delay! I added tests. Feel free to update style, naming, spelling or anything else before merge. It would be nice if you update docs by yourself because my english is a bit rusty.

**Comment by kressh** [comment]
Squashed

**Comment by soveran** [comment]
@kressh Merged! Thanks a lot :-) I will add the documentation now.

**Pull request merged**
